In [1]:
import pandas as pd
print(pd.__version__)

3.0.3

Load the data

In [2]:
path = "../data/raw/nigeria_dre_atlas_settlements.csv"

cols = pd.read_csv(path, nrows=0).columns
cols = [c for c in cols if c != "geometry"]

df = pd.read_csv(path, usecols=cols)
df.shape

(154319, 42)

In [3]:
df.head()

,geohash,lat,lon,village_name,admin_cgaz_1,admin_cgaz_2,hull_area,building_density_percent,num_buildings,large_buildings,...,ag_value,ag_yield,ag_value_area,fatalities_within_25km,fatalities_within_50km,total_incidents_50km,security_risk,num_connections,demand,demand_connection
0,s0gfrsfzgw,4.641714,5.606955,Loinbirikiri,Bayelsa,Southern Ijaw,0.021,11.19,54,0,...,1271078,43379.6,1205,11;0;3;0,13;0;8;0,17,high,54,18.4,0.341
1,s0gfwvht4d,4.686543,5.576362,Ekeni,Bayelsa,Southern Ijaw,0.063,6.42,92,1,...,1271078,43379.6,1205,6;0;3;0,13;0;7;0,15,high,92,31.9,0.347
2,s0gfwxus9d,4.701559,5.565330,Ezeotu,Bayelsa,Southern Ijaw,0.187,12.04,414,7,...,1271078,43379.6,1205,6;0;3;0,13;0;7;0,15,high,414,145.3,0.351
3,s0gfwy6but,4.692695,5.574040,Ekeni,Bayelsa,Southern Ijaw,0.298,14.94,519,34,...,1271078,43379.6,1205,6;0;3;0,13;0;7;0,15,high,519,226.6,0.437
4,s0gfx2b2vu,4.662475,5.592635,Loinbirikiri,Bayelsa,Southern Ijaw,0.024,10.99,58,0,...,1271078,43379.6,1205,11;0;3;0,13;0;7;0,16,high,58,19.7,0.340

In [4]:
df["geohash"].is_unique

True

check for missing items

In [6]:
missing = df.isna().sum()
missing[missing > 0]

nearest_hub_name    11650
mean_rwi             7130
pv_value                1
dtype: int64

check for duplicates

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df["village_name"].duplicated().sum()

np.int64(96403)

Summary numbers

In [9]:
df.describe().T[["min", "50%", "max", "mean"]]

,min,50%,max,mean
lat,4.275420,9.916077e+00,1.387676e+01,9.685701e+00
lon,2.709807,8.148435e+00,1.467439e+01,8.106990e+00
hull_area,0.001000,4.400000e-02,1.763028e+03,2.389362e-01
building_density_percent,0.730000,6.600000e+00,6.859000e+01,7.993215e+00
num_buildings,4.000000,5.000000e+01,2.615455e+06,3.207632e+02
large_buildings,0.000000,0.000000e+00,4.975630e+05,3.528168e+01
medium_buildings,0.000000,1.000000e+00,5.431380e+05,4.259654e+01
small_buildings,0.000000,4.700000e+01,1.574754e+06,2.428850e+02
very_small_structures,0.000000,1.700000e+01,3.007040e+05,6.365893e+01
population,17.000000,2.130000e+02,1.234031e+07,1.476709e+03
closest_distance_water,0.000000,8.100000e-01,6.770000e+00,1.036255e+00
dist_main_road_km,0.000000,3.690000e+00,7.516000e+01,5.731239e+00
dist_nearest_hub_km,0.000000,1.604000e+01,8.577000e+01,1.878513e+01
num_education_facilities,0.000000,0.000000e+00,7.384000e+03,8.166784e-01
num_health_facilities,0.000000,0.000000e+00,2.780000e+03,3.843921e-01
mean_rwi,-1.600000,-4.000000e-01,1.700000e+00,-3.272894e-01
distance_to_existing_transmission_lines,0.000000,2.980000e+00,1.421300e+02,6.070376e+00
distance_to_existing_hv_transmission_lines,0.000000,2.158000e+01,2.108200e+02,3.039525e+01
overlap_percentage,0.000000,0.000000e+00,1.000000e+02,2.992705e+00
distance_to_gridlight_targets,0.000000,5.187000e+00,8.526300e+01,7.518117e+00
pv_value,1213.726000,1.642894e+03,1.777306e+03,1.585218e+03
ag_area,267.600000,4.509500e+03,1.456540e+04,4.943982e+03
ag_value,84286.000000,2.650784e+06,2.513678e+07,3.578359e+06
ag_yield,8128.500000,3.574790e+04,1.074401e+05,3.940763e+04
ag_value_area,147.000000,5.780000e+02,2.121000e+03,6.616151e+02
total_incidents_50km,0.000000,5.600000e+01,1.044000e+03,9.271453e+01
num_connections,4.000000,5.000000e+01,2.615455e+06,3.207632e+02
demand,1.700000,1.840000e+01,1.427902e+06,1.478630e+02
demand_connection,0.335000,3.390000e-01,1.100000e+00,3.708411e-01

The biggest places

In [10]:
df.nlargest(8, "population")[["village_name", "admin_cgaz_1", "admin_cgaz_2", "num_buildings", "population", "demand"]]

,village_name,admin_cgaz_1,admin_cgaz_2,num_buildings,population,demand
6337,Lagos,Lagos,Alimosho,2615455,12340311,1427901.6
138855,Kan Karofi,Kano,Kano Municipal,1322903,6443921,509529.2
11140,Ibadan,Oyo,Ibadan North,1039198,4960925,621781.9
24403,Amurie,Imo,Njaba,792307,3837349,466328.2
61184,Abuja,Fct,Abuja Municipal,744894,3576670,383589.8
2131,Rumuodara,Rivers,Obia/Akpor,649926,3143246,393678.5
24785,Benin City,Edo,Ikpoba-Okha,595440,2788741,425681.4
24676,Nnewi,Anambra,Nnewi South,522564,2549063,291140.7

Are some columns copies of others?

In [11]:
(df["num_connections"] == df["num_buildings"]).mean()

np.float64(1.0)

The word columns

In [12]:
df["security_risk"].value_counts()

security_risk
high      134458
medium     18162
low         1699
Name: count, dtype: int64

In [13]:
df["main_road_access"].value_counts()

main_road_access
False    130472
True      23847
Name: count, dtype: int64

In [14]:
df["fatalities_within_25km"].head(5)

0    11;0;3;0
1     6;0;3;0
2     6;0;3;0
3     6;0;3;0
4    11;0;3;0
Name: fatalities_within_25km, dtype: str

In [15]:
df[df["mean_rwi"].isna()]["admin_cgaz_1"].value_counts().head(5)

admin_cgaz_1
Benue       758
Taraba      703
Nasarawa    596
Niger       476
Kwara       451
Name: count, dtype: int64

In [16]:
(df["mean_rwi"] == 0).sum()

np.int64(7584)

In [19]:
df["mean_rwi"].round(1).value_counts().sort_index()

mean_rwi
-1.6        1
-1.4        5
-1.3       27
-1.2      112
-1.1      305
-1.0     1026
-0.9     2216
-0.8     5341
-0.7     9530
-0.6    15627
-0.5    20766
-0.4    22563
-0.3    19626
-0.2    15351
-0.1    10866
 0.0     7584
 0.1     4988
 0.2     3473
 0.3     2353
 0.4     1665
 0.5     1195
 0.6      817
 0.7      602
 0.8      480
 0.9      301
 1.0      191
 1.1       81
 1.2       60
 1.3       15
 1.4       11
 1.5        7
 1.6        2
 1.7        2
Name: count, dtype: int64

In [20]:
df[df["nearest_hub_name"].isna()]["admin_cgaz_1"].value_counts().head(5)

admin_cgaz_1
Benue      1809
Kaduna     1724
Niger      1646
Adamawa    1488
Bauchi     1057
Name: count, dtype: int64

Data Tpes Check

In [21]:
df.dtypes

geohash                                           str
lat                                           float64
lon                                           float64
village_name                                      str
admin_cgaz_1                                      str
admin_cgaz_2                                      str
hull_area                                     float64
building_density_percent                      float64
num_buildings                                   int64
large_buildings                                 int64
medium_buildings                                int64
small_buildings                                 int64
very_small_structures                           int64
population                                      int64
closest_distance_water                        float64
main_road_access                                 bool
dist_main_road_km                             float64
nearest_hub_name                                  str
dist_nearest_hub_km                           float64
num_education_facilities                        int64
has_education_facility                           bool
num_health_facilities                           int64
has_health_facility                              bool
mean_rwi                                      float64
distance_to_existing_transmission_lines       float64
distance_to_existing_hv_transmission_lines    float64
has_nightlight                                   bool
overlap_percentage                            float64
distance_to_gridlight_targets                 float64
pv_value                                      float64
crop_types                                        str
ag_area                                       float64
ag_value                                        int64
ag_yield                                      float64
ag_value_area                                   int64
fatalities_within_25km                            str
fatalities_within_50km                            str
total_incidents_50km                            int64
security_risk                                     str
num_connections                                 int64
demand                                        float64
demand_connection                             float64
dtype: object

hidden blanks check

In [23]:
text_cols = df.select_dtypes(exclude=["number", "bool"]).columns

for c in text_cols:
    s = df[c].dropna().astype(str).str.strip().str.lower()
    hidden = s.isin(["", "na", "n/a", "none", "null", "unknown", "nan"]).sum()
    print(c, hidden)

geohash 0
village_name 0
admin_cgaz_1 0
admin_cgaz_2 0
nearest_hub_name 0
crop_types 0
fatalities_within_25km 0
fatalities_within_50km 0
security_risk 0

In [24]:
(df["has_education_facility"] == (df["num_education_facilities"] > 0)).mean()

np.float64(1.0)

In [25]:
(df["has_health_facility"] == (df["num_health_facilities"] > 0)).mean()

np.float64(1.0)